namespace UserManagement.Models;

public class Country
{
    public int Id { get; set; } // autogenerated PK

    public string Name { get; set; } = "";
    public string Code { get; set; } = "";

    public List<UserCountry> UserCountries { get; set; } = [];
}