namespace UserManagement.Models;

public class UserCountry
{
    public int Id { get; set; } // autogenerated PK

    public int UserId { get; set; }
    public User User { get; set; } = null!;

    public int CountryId { get; set; }
    public Country Country { get; set; } = null!;
}