namespace UserManagement.Models;

public class UserSession
{
    public int Id { get; set; } // autogenerated PK

    public int UserId { get; set; } // FK to User
    public User User { get; set; } = null!;

    public int UserDeviceId { get; set; } // FK to UserDevice
    public UserDevice UserDevice { get; set; } = null!;

    public string SessionToken { get; set; } = "";
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime ExpiresAt { get; set; }
    public bool IsActive { get; set; } = true;
}